var express = require('express');
var router = express.Router();

exports.week10 = function(req, res)
    allPlayers: [
      {name: "Antonio Brown", position: "WR", team: "PIT", gameTime: 2, projectedPts: 22.369, vorAvg: 78.7, cost: 8800},
      {name: "Odell Beckham Jr.", position: "WR", team: "NYG", gameTime: 3, projectedPts: 22.034, vorAvg: 76.02, cost: 8800},
      {name: "DeAndre Hopkins", position: "WR", team: "HOU", gameTime: 5, projectedPts: 22.335, vorAvg: 78.42, cost: 8700},
      {name: "Tom Brady", position: "QB", team: "NE", gameTime: 3, projectedPts: 26.715, vorAvg: 43.85, cost: 8600},
      {name: "Julian Edelman", position: "WR", team: "NE", gameTime: 3, projectedPts: 20.214, vorAvg: 61.48, cost: 8200},
      {name: "Rob Gronkowski", position: "TE", team: "NE", gameTime: 3, projectedPts: 20.771, vorAvg: 81.75, cost: 8000},
      {name: "Dez Bryant ", position: "WR", team: "DAL", gameTime: 2, projectedPts: 14.503, vorAvg: 15.86, cost: 7800},
      {name: "A.J. Green", position: "WR", team: "CIN", gameTime: 5, projectedPts: 19.933, vorAvg: 59.24, cost: 7600},
      {name: "Aaron Rodgers", position: "QB", team: "GB", gameTime: 2, projectedPts: 26.08, vorAvg: 40.43, cost: 7500},
      {name: "Calvin Johnson", position: "WR", team: "DET", gameTime: 2, projectedPts: 17.175, vorAvg: 37.2, cost: 7500},
      {name: "Demaryius Thomas", position: "WR", team: "DEN", gameTime: 3, projectedPts: 20.803, vorAvg: 66.19, cost: 7400},
      {name: "Drew Brees", position: "QB", team: "NO", gameTime: 2, projectedPts: 20.27, vorAvg: 9.15, cost: 7400},
      {name: "Brandon Marshall", position: "WR", team: "NYJ", gameTime: 1, projectedPts: 18.744, vorAvg: 49.74, cost: 7400},
      {name: "Larry Fitzgerald", position: "WR", team: "ARI", gameTime: 4, projectedPts: 17.716, vorAvg: 41.52, cost: 7400},
      {name: "Todd Gurley", position: "RB", team: "STL", gameTime: 2, projectedPts: 20.569, vorAvg: 76.44, cost: 7300},
      {name: "Emmanuel Sanders", position: "WR", team: "DEN", gameTime: 3, projectedPts: 19.112, vorAvg: 52.68, cost: 7300},
      {name: "Alshon Jeffery", position: "WR", team: "CHI", gameTime: 2, projectedPts: 20.184, vorAvg: 61.24, cost: 7100},
      {name: "Adrian Peterson", position: "RB", team: "MIN", gameTime: 3, projectedPts: 15.359, vorAvg: 31.75, cost: 7100},
      {name: "Cam Newton", position: "QB", team: "CAR", gameTime: 2, projectedPts: 19.799, vorAvg: 6.61, cost: 7000},
      {name: "Carson Palmer", position: "QB", team: "ARI", gameTime: 4, projectedPts: 19.055, vorAvg: 2.6, cost: 6900},
      {name: "Ben Roethlisberger", position: "QB", team: "PIT", gameTime: 2, projectedPts: 20.55, vorAvg: 10.65, cost: 6800},
      {name: "Amari Cooper", position: "WR", team: "OAK", gameTime: 3, projectedPts: 15.975, vorAvg: 27.62, cost: 6800},
      {name: "Mike Evans", position: "WR", team: "TB", gameTime: 2, projectedPts: 13.733, vorAvg: 9.71, cost: 6800},
      {name: "Matt Forte", position: "RB", team: "CHI", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 6800},
      {name: "Randall Cobb", position: "WR", team: "GB", gameTime: 2, projectedPts: 19.996, vorAvg: 59.74, cost: 6700},
      {name: "Eli Manning", position: "QB", team: "NYG", gameTime: 3, projectedPts: 19.715, vorAvg: 6.16, cost: 6700},
      {name: "Allen Robinson", position: "WR", team: "JAX", gameTime: 2, projectedPts: 19.117, vorAvg: 52.72, cost: 6700},
      {name: "Jarvis Landry", position: "WR", team: "MIA", gameTime: 2, projectedPts: 16.401, vorAvg: 31.02, cost: 6700},
      {name: "Marshawn Lynch", position: "RB", team: "SEA", gameTime: 4, projectedPts: 15.588, vorAvg: 33.71, cost: 6700},
      {name: "Andy Dalton", position: "QB", team: "CIN", gameTime: 5, projectedPts: 21.61, vorAvg: 16.36, cost: 6500},
      {name: "DeAngelo Williams", position: "RB", team: "PIT", gameTime: 2, projectedPts: 21.01, vorAvg: 80.22, cost: 6500},
      {name: "Mark Ingram", position: "RB", team: "NO", gameTime: 2, projectedPts: 17.053, vorAvg: 46.28, cost: 6400},
      {name: "Dion Lewis", position: "RB", team: "NE", gameTime: 3, projectedPts: 16.836, vorAvg: 44.42, cost: 6300},
      {name: "Greg Olsen", position: "TE", team: "CAR", gameTime: 2, projectedPts: 13.848, vorAvg: 21.17, cost: 6300},
      {name: "Peyton Manning", position: "QB", team: "DEN", gameTime: 3, projectedPts: 19.315, vorAvg: 4, cost: 6200},
      {name: "DeMarco Murray", position: "RB", team: "PHI", gameTime: 2, projectedPts: 18.169, vorAvg: 55.85, cost: 6200},
      {name: "Jordan Matthews", position: "WR", team: "PHI", gameTime: 2, projectedPts: 13.575, vorAvg: 8.44, cost: 6200},
      {name: "Justin Forsett", position: "RB", team: "BAL", gameTime: 2, projectedPts: 20.206, vorAvg: 73.32, cost: 6000},
      {name: "Brandin Cooks", position: "WR", team: "NO", gameTime: 2, projectedPts: 13.798, vorAvg: 10.23, cost: 6000},
      {name: "Russell Wilson", position: "QB", team: "SEA", gameTime: 4, projectedPts: 19.359, vorAvg: 4.24, cost: 5900},
      {name: "Chris Ivory", position: "RB", team: "NYJ", gameTime: 1, projectedPts: 14.141, vorAvg: 21.3, cost: 5900},
      {name: "Derek Carr", position: "QB", team: "OAK", gameTime: 3, projectedPts: 20.27, vorAvg: 9.15, cost: 5800},
      {name: "Michael Crabtree", position: "WR", team: "OAK", gameTime: 3, projectedPts: 17.822, vorAvg: 42.37, cost: 5800},
      {name: "Tyler Eifert", position: "TE", team: "CIN", gameTime: 5, projectedPts: 12.904, vorAvg: 12.91, cost: 5800},
      {name: "Allen Hurns", position: "WR", team: "JAX", gameTime: 2, projectedPts: 12.885, vorAvg: 2.93, cost: 5800},
      {name: "Sam Bradford", position: "QB", team: "PHI", gameTime: 2, projectedPts: 17.14, vorAvg: -7.71, cost: 5700},
      {name: "Latavius Murray", position: "RB", team: "OAK", gameTime: 3, projectedPts: 14.779, vorAvg: 26.77, cost: 5700},
      {name: "Blake Bortles", position: "QB", team: "JAX", gameTime: 2, projectedPts: 20.115, vorAvg: 8.31, cost: 5600},
      {name: "Doug Martin", position: "RB", team: "TB", gameTime: 2, projectedPts: 14.365, vorAvg: 23.22, cost: 5600},
      {name: "Tyrod Taylor", position: "QB", team: "BUF", gameTime: 1, projectedPts: 18.213, vorAvg: -1.93, cost: 5500},
      {name: "Eddie Lacy", position: "RB", team: "GB", gameTime: 2, projectedPts: 17.946, vorAvg: 53.94, cost: 5500},
      {name: "Joe Flacco", position: "QB", team: "BAL", gameTime: 2, projectedPts: 17.825, vorAvg: -4.02, cost: 5500},
      {name: "Jeremy Maclin", position: "WR", team: "KC", gameTime: 3, projectedPts: 15.67, vorAvg: 25.18, cost: 5500},
      {name: "Martavis Bryant", position: "WR", team: "PIT", gameTime: 2, projectedPts: 13.666, vorAvg: 9.17, cost: 5500},
      {name: "John Brown", position: "WR", team: "ARI", gameTime: 4, projectedPts: 13.483, vorAvg: 7.71, cost: 5500},
      {name: "LeSean McCoy", position: "RB", team: "BUF", gameTime: 1, projectedPts: 12.929, vorAvg: 10.9, cost: 5500},
      {name: "Brian Hoyer", position: "QB", team: "HOU", gameTime: 5, projectedPts: 18.88, vorAvg: 1.66, cost: 5400},
      {name: "Matthew Stafford", position: "QB", team: "DET", gameTime: 2, projectedPts: 18.095, vorAvg: -2.56, cost: 5400},
      {name: "Lamar Miller", position: "RB", team: "MIA", gameTime: 2, projectedPts: 14.864, vorAvg: 27.5, cost: 5400},
      {name: "DeSean Jackson ", position: "WR", team: "WAS", gameTime: 2, projectedPts: 14.163, vorAvg: 13.14, cost: 5400},
      {name: "Ryan Tannehill", position: "QB", team: "MIA", gameTime: 2, projectedPts: 17.17, vorAvg: -7.55, cost: 5300},
      {name: "Marcus Mariota", position: "QB", team: "TEN", gameTime: 2, projectedPts: 16.1, vorAvg: -13.31, cost: 5300},
      {name: "Eric Decker", position: "WR", team: "NYJ", gameTime: 1, projectedPts: 15.652, vorAvg: 25.04, cost: 5300},
      {name: "Jeremy Hill", position: "RB", team: "CIN", gameTime: 5, projectedPts: 14.134, vorAvg: 21.24, cost: 5300},
      {name: "James Jones", position: "WR", team: "GB", gameTime: 2, projectedPts: 11.967, vorAvg: -4.4, cost: 5300},
      {name: "Landry Jones", position: "QB", team: "PIT", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 5300},
      {name: "Kirk Cousins", position: "QB", team: "WAS", gameTime: 2, projectedPts: 18.43, vorAvg: -0.76, cost: 5200},
      {name: "Travis Benjamin", position: "WR", team: "CLE", gameTime: 2, projectedPts: 14.571, vorAvg: 16.4, cost: 5200},
      {name: "Ryan Fitzpatrick", position: "QB", team: "NYJ", gameTime: 1, projectedPts: 18.92, vorAvg: 1.88, cost: 5100},
      {name: "Teddy Bridgewater", position: "QB", team: "MIN", gameTime: 3, projectedPts: 15.685, vorAvg: -15.54, cost: 5100},
      {name: "Stefon Diggs", position: "WR", team: "MIN", gameTime: 3, projectedPts: 15.549, vorAvg: 24.21, cost: 5100},
      {name: "Jay Cutler", position: "QB", team: "CHI", gameTime: 2, projectedPts: 15.435, vorAvg: -16.89, cost: 5100},
      {name: "Jason Witten", position: "TE", team: "DAL", gameTime: 2, projectedPts: 10.864, vorAvg: -4.94, cost: 5100},
      {name: "Josh McCown", position: "QB", team: "CLE", gameTime: 2, projectedPts: 17.48, vorAvg: -5.88, cost: 5000},
      {name: "Alex Smith", position: "QB", team: "KC", gameTime: 3, projectedPts: 15.545, vorAvg: -16.3, cost: 5000},
      {name: "Sammy Watkins", position: "WR", team: "BUF", gameTime: 1, projectedPts: 14.703, vorAvg: 17.46, cost: 5000},
      {name: "Jameis Winston", position: "QB", team: "TB", gameTime: 2, projectedPts: 14.21, vorAvg: -23.48, cost: 5000},
      {name: "Nick Foles", position: "QB", team: "STL", gameTime: 2, projectedPts: 14.02, vorAvg: -24.51, cost: 5000},
      {name: "Matt Cassel ", position: "QB", team: "DAL", gameTime: 2, projectedPts: 13.995, vorAvg: -24.64, cost: 5000},
      {name: "EJ Manuel", position: "QB", team: "BUF", gameTime: 1, projectedPts: 0, vorAvg: -100, cost: 5000},
      {name: "Johnny Manziel", position: "QB", team: "CLE", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 5000},
      {name: "Brandon Weeden", position: "QB", team: "DAL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 5000},
      {name: "Luke McCown", position: "QB", team: "NO", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 5000},
      {name: "Mike Vick", position: "QB", team: "PIT", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 5000},
      {name: "Darren McFadden", position: "RB", team: "DAL", gameTime: 2, projectedPts: 18.296, vorAvg: 56.94, cost: 4900},
      {name: "Jimmy Graham", position: "TE", team: "SEA", gameTime: 4, projectedPts: 12.953, vorAvg: 13.34, cost: 4900},
      {name: "Willie Snead", position: "WR", team: "NO", gameTime: 2, projectedPts: 12.278, vorAvg: -1.92, cost: 4900},
      {name: "LeGarrette Blount", position: "RB", team: "NE", gameTime: 3, projectedPts: 11.941, vorAvg: 2.43, cost: 4900},
      {name: "James Starks", position: "RB", team: "GB", gameTime: 2, projectedPts: 8.474, vorAvg: -27.31, cost: 4900},
      {name: "Charcandrick West", position: "RB", team: "KC", gameTime: 3, projectedPts: 14.255, vorAvg: 22.28, cost: 4800},
      {name: "T.J. Yeldon", position: "RB", team: "JAX", gameTime: 2, projectedPts: 14.092, vorAvg: 20.88, cost: 4800},
      {name: "Gary Barnidge", position: "TE", team: "CLE", gameTime: 2, projectedPts: 14.022, vorAvg: 22.7, cost: 4800},
      {name: "Pierre Garcon", position: "WR", team: "WAS", gameTime: 2, projectedPts: 13.24, vorAvg: 5.77, cost: 4800},
      {name: "Tavon Austin", position: "WR", team: "STL", gameTime: 2, projectedPts: 13.093, vorAvg: 4.59, cost: 4800},
      {name: "Jeremy Langford", position: "RB", team: "CHI", gameTime: 2, projectedPts: 12.029, vorAvg: 3.18, cost: 4800},
      {name: "Travis Kelce", position: "TE", team: "KC", gameTime: 3, projectedPts: 11.596, vorAvg: 1.47, cost: 4800},
      {name: "Martellus Bennett", position: "TE", team: "CHI", gameTime: 2, projectedPts: 14.641, vorAvg: 28.11, cost: 4700},
      {name: "Giovani Bernard", position: "RB", team: "CIN", gameTime: 5, projectedPts: 13.429, vorAvg: 15.19, cost: 4700},
      {name: "Rishard Matthews", position: "WR", team: "MIA", gameTime: 2, projectedPts: 13, vorAvg: 3.85, cost: 4700},
      {name: "Delanie Walker", position: "TE", team: "TEN", gameTime: 2, projectedPts: 12.145, vorAvg: 6.27, cost: 4700},
      {name: "Kendall Wright", position: "WR", team: "TEN", gameTime: 2, projectedPts: 11.361, vorAvg: -9.24, cost: 4700},
      {name: "Vincent Jackson", position: "WR", team: "TB", gameTime: 2, projectedPts: 10.626, vorAvg: -15.11, cost: 4700},
      {name: "Jordan Reed", position: "TE", team: "WAS", gameTime: 2, projectedPts: 13.788, vorAvg: 20.65, cost: 4600},
      {name: "Golden Tate", position: "WR", team: "DET", gameTime: 2, projectedPts: 13.12, vorAvg: 4.81, cost: 4600},
      {name: "Chris Johnson", position: "RB", team: "ARI", gameTime: 4, projectedPts: 9.789, vorAvg: -16.03, cost: 4600},
      {name: "Kamar Aiken", position: "WR", team: "BAL", gameTime: 2, projectedPts: 13.058, vorAvg: 4.31, cost: 4500},
      {name: "Nate Washington", position: "WR", team: "HOU", gameTime: 5, projectedPts: 13.564, vorAvg: 8.36, cost: 4400},
      {name: "Jonathan Stewart", position: "RB", team: "CAR", gameTime: 2, projectedPts: 14.156, vorAvg: 21.43, cost: 4300},
      {name: "Marvin Jones", position: "WR", team: "CIN", gameTime: 5, projectedPts: 11.394, vorAvg: -8.98, cost: 4300},
      {name: "Shane Vereen", position: "RB", team: "NYG", gameTime: 3, projectedPts: 10.627, vorAvg: -8.84, cost: 4300},
      {name: "Benjamin Watson", position: "TE", team: "NO", gameTime: 2, projectedPts: 10.33, vorAvg: -9.61, cost: 4300},
      {name: "Davante Adams", position: "WR", team: "GB", gameTime: 2, projectedPts: 12.795, vorAvg: 2.21, cost: 4200},
      {name: "Breshad Perriman ", position: "WR", team: "BAL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 4200},
      {name: "Brandon LaFell", position: "WR", team: "NE", gameTime: 3, projectedPts: 14.385, vorAvg: 14.91, cost: 4100},
      {name: "Charles Clay", position: "TE", team: "BUF", gameTime: 1, projectedPts: 10.429, vorAvg: -8.74, cost: 4100},
      {name: "Ronnie Hillman", position: "RB", team: "DEN", gameTime: 3, projectedPts: 12.861, vorAvg: 10.32, cost: 4000},
      {name: "Duke Johnson Jr.", position: "RB", team: "CLE", gameTime: 2, projectedPts: 11.252, vorAvg: -3.48, cost: 4000},
      {name: "Alfred Blue", position: "RB", team: "HOU", gameTime: 5, projectedPts: 10.126, vorAvg: -13.14, cost: 4000},
      {name: "Danny Amendola", position: "WR", team: "NE", gameTime: 3, projectedPts: 6.01, vorAvg: -51.99, cost: 4000},
      {name: "Victor Cruz ", position: "WR", team: "NYG", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 4000},
      {name: "Rueben Randle", position: "WR", team: "NYG", gameTime: 3, projectedPts: 12.943, vorAvg: 3.4, cost: 3900},
      {name: "Arizona", position: "DEF", team: "ARI", gameTime: 4, projectedPts: 7.743, vorAvg: 23.21, cost: 3900},
      {name: "Michael Floyd", position: "WR", team: "ARI", gameTime: 4, projectedPts: 10.727, vorAvg: -14.31, cost: 3800},
      {name: "C.J. Anderson", position: "RB", team: "DEN", gameTime: 3, projectedPts: 9.418, vorAvg: -19.21, cost: 3800},
      {name: "Marquess Wilson", position: "WR", team: "CHI", gameTime: 2, projectedPts: 8.868, vorAvg: -29.16, cost: 3800},
      {name: "Rashad Jennings", position: "RB", team: "NYG", gameTime: 3, projectedPts: 8.195, vorAvg: -29.7, cost: 3800},
      {name: "Terrance Williams", position: "WR", team: "DAL", gameTime: 2, projectedPts: 7.487, vorAvg: -40.19, cost: 3800},
      {name: "Karlos Williams", position: "RB", team: "BUF", gameTime: 1, projectedPts: 4.88, vorAvg: -58.14, cost: 3800},
      {name: "Mike Wallace", position: "WR", team: "MIN", gameTime: 3, projectedPts: 10.976, vorAvg: -12.32, cost: 3700},
      {name: "Julius Thomas ", position: "TE", team: "JAX", gameTime: 2, projectedPts: 10.407, vorAvg: -8.94, cost: 3700},
      {name: "Antonio Andrews", position: "RB", team: "TEN", gameTime: 2, projectedPts: 10.363, vorAvg: -11.11, cost: 3700},
      {name: "Andre Ellington", position: "RB", team: "ARI", gameTime: 4, projectedPts: 7.12, vorAvg: -38.93, cost: 3700},
      {name: "Percy Harvin", position: "WR", team: "BUF", gameTime: 1, projectedPts: 0, vorAvg: -100, cost: 3700},
      {name: "Robert Woods", position: "WR", team: "BUF", gameTime: 1, projectedPts: 11.006, vorAvg: -12.08, cost: 3600},
      {name: "St. Louis", position: "DEF", team: "STL", gameTime: 2, projectedPts: 9.571, vorAvg: 52.29, cost: 3600},
      {name: "Marlon Brown ", position: "WR", team: "BAL", gameTime: 2, projectedPts: 9.322, vorAvg: -25.53, cost: 3600},
      {name: "Dwayne Harris", position: "WR", team: "NYG", gameTime: 3, projectedPts: 9.075, vorAvg: -27.5, cost: 3600},
      {name: "Darren Sproles", position: "RB", team: "PHI", gameTime: 2, projectedPts: 8.37, vorAvg: -28.2, cost: 3600},
      {name: "Kenny Britt", position: "WR", team: "STL", gameTime: 2, projectedPts: 6.332, vorAvg: -49.42, cost: 3600},
      {name: "Charles Sims", position: "RB", team: "TB", gameTime: 2, projectedPts: 10.284, vorAvg: -11.79, cost: 3500},
      {name: "Jamison Crowder", position: "WR", team: "WAS", gameTime: 2, projectedPts: 8.925, vorAvg: -28.7, cost: 3500},
      {name: "Ryan Mathews", position: "RB", team: "PHI", gameTime: 2, projectedPts: 8.6, vorAvg: -26.23, cost: 3500},
      {name: "Chris Hogan", position: "WR", team: "BUF", gameTime: 1, projectedPts: 7.139, vorAvg: -42.97, cost: 3500},
      {name: "Seattle", position: "DEF", team: "SEA", gameTime: 4, projectedPts: 6.171, vorAvg: -1.81, cost: 3500},
      {name: "Taiwan Jones", position: "RB", team: "OAK", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3500},
      {name: "Marcel Reece", position: "RB", team: "OAK", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3500},
      {name: "Thomas Rawls", position: "RB", team: "SEA", gameTime: 4, projectedPts: 0, vorAvg: -100, cost: 3500},
      {name: "Ted Ginn Jr.", position: "WR", team: "CAR", gameTime: 2, projectedPts: 10.621, vorAvg: -15.15, cost: 3400},
      {name: "Marques Colston", position: "WR", team: "NO", gameTime: 2, projectedPts: 10.428, vorAvg: -16.7, cost: 3400},
      {name: "Denver", position: "DEF", team: "DEN", gameTime: 3, projectedPts: 9.429, vorAvg: 50.03, cost: 3400},
      {name: "Doug Baldwin", position: "WR", team: "SEA", gameTime: 4, projectedPts: 9.061, vorAvg: -27.62, cost: 3400},
      {name: "Nelson Agholor ", position: "WR", team: "PHI", gameTime: 2, projectedPts: 7.61, vorAvg: -39.21, cost: 3400},
      {name: "Isaiah Crowell", position: "RB", team: "CLE", gameTime: 2, projectedPts: 6.991, vorAvg: -40.03, cost: 3400},
      {name: "Ameer Abdullah", position: "RB", team: "DET", gameTime: 2, projectedPts: 4.76, vorAvg: -59.17, cost: 3400},
      {name: "Eddie Royal", position: "WR", team: "CHI", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3400},
      {name: "David Johnson", position: "RB", team: "ARI", gameTime: 4, projectedPts: 0, vorAvg: -100, cost: 3400},
      {name: "Matt Jones", position: "RB", team: "WAS", gameTime: 2, projectedPts: 11.921, vorAvg: 2.26, cost: 3300},
      {name: "Theo Riddick", position: "RB", team: "DET", gameTime: 2, projectedPts: 11.529, vorAvg: -1.11, cost: 3300},
      {name: "Eric Ebron", position: "TE", team: "DET", gameTime: 2, projectedPts: 11.11, vorAvg: -2.79, cost: 3300},
      {name: "Dexter McCluster", position: "RB", team: "TEN", gameTime: 2, projectedPts: 10.079, vorAvg: -13.54, cost: 3300},
      {name: "Alfred Morris", position: "RB", team: "WAS", gameTime: 2, projectedPts: 8.325, vorAvg: -28.59, cost: 3300},
      {name: "Carolina", position: "DEF", team: "CAR", gameTime: 2, projectedPts: 8.057, vorAvg: 28.2, cost: 3300},
      {name: "Cincinnati", position: "DEF", team: "CIN", gameTime: 5, projectedPts: 6.486, vorAvg: 3.2, cost: 3300},
      {name: "Javorius Allen", position: "RB", team: "BAL", gameTime: 2, projectedPts: 6.03, vorAvg: -48.28, cost: 3300},
      {name: "Bryan Walters", position: "WR", team: "JAX", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3300},
      {name: "Chris Thompson", position: "RB", team: "WAS", gameTime: 2, projectedPts: 11.61, vorAvg: -0.41, cost: 3200},
      {name: "Chris Givens ", position: "WR", team: "BAL", gameTime: 2, projectedPts: 8.726, vorAvg: -30.29, cost: 3200},
      {name: "Joique Bell", position: "RB", team: "DET", gameTime: 2, projectedPts: 8.167, vorAvg: -29.94, cost: 3200},
      {name: "Green Bay", position: "DEF", team: "GB", gameTime: 2, projectedPts: 7.543, vorAvg: 20.02, cost: 3200},
      {name: "New England", position: "DEF", team: "NE", gameTime: 3, projectedPts: 7.257, vorAvg: 15.47, cost: 3200},
      {name: "Chris Polk", position: "RB", team: "HOU", gameTime: 5, projectedPts: 6.575, vorAvg: -43.6, cost: 3200},
      {name: "Orleans Darkwa", position: "RB", team: "NYG", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3200},
      {name: "Dorial Green-Beckham ", position: "WR", team: "TEN", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3200},
      {name: "Harry Douglas ", position: "WR", team: "TEN", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3200},
      {name: "Adam Humphries", position: "WR", team: "TB", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3200},
      {name: "Jerricho Cotchery ", position: "WR", team: "CAR", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3200},
      {name: "Knile Davis", position: "RB", team: "KC", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3200},
      {name: "Kenny Stills", position: "WR", team: "MIA", gameTime: 2, projectedPts: 7.808, vorAvg: -37.63, cost: 3100},
      {name: "Jermaine Kearse", position: "WR", team: "SEA", gameTime: 4, projectedPts: 7.353, vorAvg: -41.26, cost: 3100},
      {name: "Corey Brown", position: "WR", team: "CAR", gameTime: 2, projectedPts: 6.714, vorAvg: -46.37, cost: 3100},
      {name: "Justin Hunter", position: "WR", team: "TEN", gameTime: 2, projectedPts: 6.208, vorAvg: -50.41, cost: 3100},
      {name: "C.J. Spiller", position: "RB", team: "NO", gameTime: 2, projectedPts: 12.803, vorAvg: 9.82, cost: 3000},
      {name: "Zach Ertz", position: "TE", team: "PHI", gameTime: 2, projectedPts: 11.356, vorAvg: -0.63, cost: 3000},
      {name: "Richard Rodgers", position: "TE", team: "GB", gameTime: 2, projectedPts: 11.259, vorAvg: -1.48, cost: 3000},
      {name: "Cecil Shorts III", position: "WR", team: "HOU", gameTime: 5, projectedPts: 10.985, vorAvg: -12.25, cost: 3000},
      {name: "Heath Miller", position: "TE", team: "PIT", gameTime: 2, projectedPts: 9.648, vorAvg: -15.58, cost: 3000},
      {name: "Tyler Lockett", position: "WR", team: "SEA", gameTime: 4, projectedPts: 9.608, vorAvg: -23.25, cost: 3000},
      {name: "Bilal Powell", position: "RB", team: "NYJ", gameTime: 1, projectedPts: 8.07, vorAvg: -30.78, cost: 3000},
      {name: "Markus Wheaton", position: "WR", team: "PIT", gameTime: 2, projectedPts: 7.975, vorAvg: -36.29, cost: 3000},
      {name: "Jonathan Grimes", position: "RB", team: "HOU", gameTime: 5, projectedPts: 7.938, vorAvg: -31.91, cost: 3000},
      {name: "Mohamed Sanu", position: "WR", team: "CIN", gameTime: 5, projectedPts: 7.704, vorAvg: -38.46, cost: 3000},
      {name: "Andrew Hawkins", position: "WR", team: "CLE", gameTime: 2, projectedPts: 7.653, vorAvg: -38.86, cost: 3000},
      {name: "Jeremy Kerley ", position: "WR", team: "NYJ", gameTime: 1, projectedPts: 7.62, vorAvg: -39.13, cost: 3000},
      {name: "Kyle Rudolph", position: "TE", team: "MIN", gameTime: 3, projectedPts: 7.485, vorAvg: -34.5, cost: 3000},
      {name: "Pittsburgh", position: "DEF", team: "PIT", gameTime: 2, projectedPts: 7.343, vorAvg: 16.84, cost: 3000},
      {name: "Albert Wilson", position: "WR", team: "KC", gameTime: 3, projectedPts: 6.892, vorAvg: -44.94, cost: 3000},
      {name: "Marqise Lee ", position: "WR", team: "JAX", gameTime: 2, projectedPts: 6.605, vorAvg: -47.24, cost: 3000},
      {name: "Antone Smith ", position: "RB", team: "CHI", gameTime: 2, projectedPts: 5.83, vorAvg: -49.99, cost: 3000},
      {name: "Christine Michael ", position: "RB", team: "DAL", gameTime: 2, projectedPts: 4.841, vorAvg: -58.47, cost: 3000},
      {name: "Tre Mason", position: "RB", team: "STL", gameTime: 2, projectedPts: 4.24, vorAvg: -63.63, cost: 3000},
      {name: "Ty Montgomery", position: "WR", team: "GB", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Bishop Sankey", position: "RB", team: "TEN", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Toby Gerhart", position: "RB", team: "JAX", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Josh Huff", position: "WR", team: "PHI", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Taylor Gabriel", position: "WR", team: "CLE", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Donteea Dye", position: "WR", team: "TB", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Zac Stacy", position: "RB", team: "NYJ", gameTime: 1, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Dwayne Bowe ", position: "WR", team: "CLE", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Riley Cooper", position: "WR", team: "PHI", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Marc Mariani ", position: "WR", team: "CHI", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Jonas Gray", position: "RB", team: "MIA", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Andre Williams", position: "RB", team: "NYG", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Cameron Artis-Payne", position: "RB", team: "CAR", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Damien Williams", position: "RB", team: "MIA", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Daniel Herron", position: "RB", team: "BUF", gameTime: 1, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Denard Robinson", position: "RB", team: "JAX", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Jerick McKinnon", position: "RB", team: "MIN", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Matt Asiata", position: "RB", team: "MIN", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Robert Turbin", position: "RB", team: "CLE", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Aaron Dobson", position: "WR", team: "NE", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Adam Thielen", position: "WR", team: "MIN", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Brandon Coleman", position: "WR", team: "NO", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Brian Hartline", position: "WR", team: "CLE", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Cole Beasley", position: "WR", team: "DAL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Darrius Heyward-Bey", position: "WR", team: "PIT", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Jarius Wright", position: "WR", team: "MIN", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Lucky Whitehead", position: "WR", team: "DAL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Miles Austin", position: "WR", team: "PHI", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Stedman Bailey", position: "WR", team: "STL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Mike Tolbert", position: "RB", team: "CAR", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Ryan Grant", position: "WR", team: "WAS", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Benny Cunningham ", position: "RB", team: "STL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Fred Jackson", position: "RB", team: "SEA", gameTime: 4, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Chris Conley", position: "WR", team: "KC", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Keith Mumphery", position: "WR", team: "HOU", gameTime: 5, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Lance Moore", position: "WR", team: "DET", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Jay Ajayi ", position: "RB", team: "MIA", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 3000},
      {name: "Buffalo", position: "DEF", team: "BUF", gameTime: 1, projectedPts: 7.7, vorAvg: 22.52, cost: 2900},
      {name: "Crockett Gillmore", position: "TE", team: "BAL", gameTime: 2, projectedPts: 8.933, vorAvg: -21.83, cost: 2800},
      {name: "Austin Seferian-Jenkins", position: "TE", team: "TB", gameTime: 2, projectedPts: 8.114, vorAvg: -29, cost: 2800},
      {name: "Baltimore", position: "DEF", team: "BAL", gameTime: 2, projectedPts: 7.443, vorAvg: 18.43, cost: 2800},
      {name: "Minnesota", position: "DEF", team: "MIN", gameTime: 3, projectedPts: 5.8, vorAvg: -7.71, cost: 2800},
      {name: "Larry Donnell", position: "TE", team: "NYG", gameTime: 3, projectedPts: 10.796, vorAvg: -5.53, cost: 2700},
      {name: "Jordan Cameron", position: "TE", team: "MIA", gameTime: 2, projectedPts: 10.391, vorAvg: -9.08, cost: 2700},
      {name: "Philadelphia", position: "DEF", team: "PHI", gameTime: 2, projectedPts: 7.957, vorAvg: 26.61, cost: 2700},
      {name: "Kansas City", position: "DEF", team: "KC", gameTime: 3, projectedPts: 5.5, vorAvg: -12.48, cost: 2600},
      {name: "Jacksonville", position: "DEF", team: "JAX", gameTime: 2, projectedPts: 4.843, vorAvg: -22.94, cost: 2600},
      {name: "Houston", position: "DEF", team: "HOU", gameTime: 5, projectedPts: 3.271, vorAvg: -47.95, cost: 2600},
      {name: "Vernon Davis ", position: "TE", team: "DEN", gameTime: 3, projectedPts: 9.239, vorAvg: -19.16, cost: 2500},
      {name: "Jared Cook", position: "TE", team: "STL", gameTime: 2, projectedPts: 7.25, vorAvg: -36.56, cost: 2500},
      {name: "Dallas", position: "DEF", team: "DAL", gameTime: 2, projectedPts: 7.114, vorAvg: 13.2, cost: 2500},
      {name: "Miami", position: "DEF", team: "MIA", gameTime: 2, projectedPts: 6.186, vorAvg: -1.57, cost: 2500},
      {name: "Washington", position: "DEF", team: "WAS", gameTime: 2, projectedPts: 5.814, vorAvg: -7.49, cost: 2500},
      {name: "Tampa Bay", position: "DEF", team: "TB", gameTime: 2, projectedPts: 4.843, vorAvg: -22.94, cost: 2500},
      {name: "Anthony Fasano", position: "TE", team: "TEN", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Scott Chandler", position: "TE", team: "NE", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Dion Sims ", position: "TE", team: "MIA", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Lance Kendricks ", position: "TE", team: "STL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Darren Fells", position: "TE", team: "ARI", gameTime: 4, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Jermaine Gresham", position: "TE", team: "ARI", gameTime: 4, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Will Tye ", position: "TE", team: "NYG", gameTime: 3, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "Maxx Williams ", position: "TE", team: "BAL", gameTime: 2, projectedPts: 0, vorAvg: -100, cost: 2500},
      {name: "New Orleans", position: "DEF", team: "NO", gameTime: 2, projectedPts: 5.357, vorAvg: -14.76, cost: 2300},
      {name: "Tennessee", position: "DEF", team: "TEN", gameTime: 2, projectedPts: 6.071, vorAvg: -3.4, cost: 2200},
      {name: "Chicago", position: "DEF", team: "CHI", gameTime: 2, projectedPts: 4.914, vorAvg: -21.81, cost: 2200},
      {name: "Oakland", position: "DEF", team: "OAK", gameTime: 3, projectedPts: 5.471, vorAvg: -12.95, cost: 2100},
      {name: "Detroit", position: "DEF", team: "DET", gameTime: 2, projectedPts: 2.014, vorAvg: -67.95, cost: 2100},
      {name: "Cleveland", position: "DEF", team: "CLE", gameTime: 2, projectedPts: 6.271, vorAvg: -0.22, cost: 2000}
    ]
  });
});

module.exports = router;
