// See http://codepen.io/mmmaaatttttt/pen/OMzNqY?editors=001

var movies = [
  {"title": "Wayne's World", "releaseYear": 1992, "rating": "PG-13", "runtime": 94, "freshness": 0.85},
  {"title": "Gone with the Wind", "releaseYear": 1939, "rating": "G", "runtime": 238, "freshness": 0.94},
  {"title": "Star Wars Episode I: The Phantom Menace", "releaseYear": 1999, "rating": "PG", "runtime": 136, "freshness": 0.56},
  {"title": "Star Wars Episode II: Attack of the Clones", "releaseYear": 2002, "rating": "PG", "runtime": 142, "freshness": 0.66},
  {"title": "Star Wars Episode III: Revenge of the Sith", "releaseYear": 2005, "rating": "PG-13", "runtime": 140, "freshness": 0.79},
  {"title": "Star Wars Episode IV: A New Hope", "releaseYear": 1977, "rating": "PG", "runtime": 121, "freshness": 0.94},
  {"title": "Star Wars Episode V: The Empire Strikes Back", "releaseYear": 1980, "rating": "PG", "runtime": 124, "freshness": 0.94},
  {"title": "Star Wars Episode VI: Return of the Jedi", "releaseYear": 1983, "rating": "PG", "runtime": 131, "freshness": 0.80},
  {"title": "E.T. the Extra-Terrestrial", "releaseYear": 1982, "rating": "PG", "runtime": 115, "freshness": 0.98},
  {"title": "Titanic", "releaseYear": 1997, "rating": "PG-13", "runtime": 194, "freshness": 0.88},
  {"title": "Jaws", "releaseYear": 1975, "rating": "PG", "runtime": 124, "freshness": 0.97},
  {"title": "The Exorcist", "releaseYear": 1973, "rating": "R", "runtime": 122, "freshness": 0.87},
  {"title": "Snow White and the Seven Dwarfs", "releaseYear": 1937, "rating": "G", "runtime": 83, "freshness": 0.98},
  {"title": "Ben-Hur", "releaseYear": 1959, "rating": "G", "runtime": 212, "freshness": 0.88},
  {"title": "Avatar", "releaseYear": 2009, "rating": "PG-13", "runtime": 162, "freshness": 0.83},
  {"title": "Jurassic Park", "releaseYear": 1993, "rating": "PG-13", "runtime": 127, "freshness": 0.93},
  {"title": "The Lion King", "releaseYear": 1994, "rating": "G", "runtime": 89, "freshness": 0.91},
  {"title": "Raiders of the Lost Ark", "releaseYear": 1981, "rating": "PG", "runtime": 115, "freshness": 0.96},
  {"title": "Fantasia", "releaseYear": 1940, "rating": "G", "runtime": 125, "freshness": 0.96},
  {"title": "The Graduate", "releaseYear": 1967, "rating": "PG", "runtime": 106, "freshness": 0.89},
  {"title": "Jurassic World", "releaseYear": 2015, "rating": "PG-13", "runtime": 124, "freshness": 0.71},
  {"title": "The Godfather", "releaseYear": 1972, "rating": "R", "runtime": 175, "freshness": 0.99},
  {"title": "Forrest Gump", "releaseYear": 1994, "rating": "PG-13", "runtime": 141, "freshness": 0.72},
  {"title": "Mary Poppins", "releaseYear": 1964, "rating": "G", "runtime": 139, "freshness": 1.00},
  {"title": "Marvel's The Avengers", "releaseYear": 2012, "rating": "PG-13", "runtime": 142, "freshness": 0.92},
  {"title": "The Dark Knight", "releaseYear": 2008, "rating": "PG-13", "runtime": 150, "freshness": 0.94},
  {"title": "Independence Day", "releaseYear": 1996, "rating": "PG-13", "runtime": 153, "freshness": 0.60},
  {"title": "Home Alone", "releaseYear": 1990, "rating": "PG", "runtime": 105, "freshness": 0.55},
  {"title": "My Fair Lady", "releaseYear": 1964, "rating": "G", "runtime": 170, "freshness": 0.96},
  {"title": "Back to the Future", "releaseYear": 1985, "rating": "PG", "runtime": 111, "freshness": 0.96},
  {"title": "The Sixth Sense", "releaseYear": 1999, "rating": "PG-13", "runtime": 107, "freshness": 0.85},
  {"title": "Tootsie", "releaseYear": 1982, "rating": "PG", "runtime": 119, "freshness": 0.88},
  {"title": "West Side Story", "releaseYear": 1961, "rating": "G", "runtime": 151, "freshness": 0.94},
  {"title": "Lawrence of Arabia", "releaseYear": 1962, "rating": "PG", "runtime": 216, "freshness": 0.99},
  {"title": "The Rocky Horror Picture Show", "releaseYear": 1975, "rating": "R", "runtime": 100, "freshness": 0.80},
  {"title": "Rocky", "releaseYear": 1976, "rating": "PG", "runtime": 119, "freshness": 0.93},
  {"title": "Men in Black", "releaseYear": 1997, "rating": "PG-13", "runtime": 97, "freshness": 0.92},
  {"title": "Mrs. Doubtfire", "releaseYear": 1993, "rating": "PG-13", "runtime": 125, "freshness": 0.71},
  {"title": "Aladdin", "releaseYear": 1992, "rating": "G", "runtime": 90, "freshness": 0.94},
  {"title": "Toy Story 3", "releaseYear": 2010, "rating": "G", "runtime": 103, "freshness": 0.99},
  {"title": "The Hunger Games", "releaseYear": 2012, "rating": "PG-13", "runtime": 142, "freshness": 0.84},
  {"title": "Pirates of the Caribbean: The Curse of the Black Pearl", "releaseYear": 2003, "rating": "PG-13", "runtime": 135, "freshness": 0.79},
  {"title": "Terminator 2: Judgment Day", "releaseYear": 1991, "rating": "R", "runtime": 137, "freshness": 0.93},
  {"title": "Crocodile Dundee", "releaseYear": 1986, "rating": "PG-13", "runtime": 93, "freshness": 0.89},
  {"title": "Office Space", "releaseYear": 1999, "rating": "R", "runtime": 89, "freshness": 0.79},
  {"title": "Iron Man", "releaseYear": 2008, "rating": "PG-13", "runtime": 126, "freshness": 0.94},
  {"title": "Saturday Night Fever", "releaseYear": 1977, "rating": "R", "runtime": 118, "freshness": 0.88},
  {"title": "Up", "releaseYear": 2009, "rating": "PG", "runtime": 96, "freshness": 0.98},
  {"title": "Who Framed Roger Rabbit", "releaseYear": 1988, "rating": "PG", "runtime": 103, "freshness": 0.97},
  {"title": "The Room", "releaseYear": 2003, "rating": "R", "runtime": 99, "freshness": 0.35},
  {"title": "Troll 2", "releaseYear": 1990, "rating": "PG-13", "runtime": 95, "freshness": 0.06},
  {"title": "Battlefield Earth", "releaseYear": 2000, "rating": "PG-13", "runtime": 118, "freshness": 0.03},
  {"title": "Transformers: Revenge of the Fallen", "releaseYear": 2009, "rating": "PG-13", "runtime": 150, "freshness": 0.19},
  {"title": "Snakes on a Plane", "releaseYear": 2006, "rating": "R", "runtime": 105, "freshness": 0.68},
  {"title": "Alvin and the Chipmunks", "releaseYear": 2007, "rating": "PG", "runtime": 92, "freshness": 0.27},
  {"title": "Crank", "releaseYear": 2006, "rating": "R", "runtime": 88, "freshness": 0.61},
  {"title": "2001: A Space Odyssey", "releaseYear": 1968, "rating": "G", "runtime": 149, "freshness": 0.96},
  {"title": "Fight Club", "releaseYear": 1999, "rating": "R", "runtime": 139, "freshness": 0.79},
  {"title": "The Matrix", "releaseYear": 1999, "rating": "R", "runtime": 136, "freshness": 0.87},
  {"title": "The Matrix Reloaded", "releaseYear": 2003, "rating": "R", "runtime": 138, "freshness": 0.73},
  {"title": "The Matrix Revolutions", "releaseYear": 2003, "rating": "R", "runtime": 129, "freshness": 0.36},
  {"title": "Little Shop of Horrors", "releaseYear": 1986, "rating": "PG-13", "runtime": 94, "freshness": 0.90},
  {"title": "Groundhog Day", "releaseYear": 1993, "rating": "PG", "runtime": 101, "freshness": 0.96},
  {"title": "The Shawshank Redemption", "releaseYear": 1994, "rating": "R", "runtime": 142, "freshness": 0.91},
  {"title": "Pulp Fiction", "releaseYear": 1994, "rating": "R", "runtime": 154, "freshness": 0.93},
  {"title": "Inception", "releaseYear": 2010, "rating": "PG-13", "runtime": 148, "freshness": 0.86},
  {"title": "Memento", "releaseYear": 2000, "rating": "R", "runtime": 113, "freshness": 0.92},
  {"title": "Alien", "releaseYear": 1979, "rating": "R", "runtime": 117, "freshness": 0.97},
  {"title": "Aliens", "releaseYear": 1986, "rating": "R", "runtime": 137, "freshness": 0.98},
  {"title": "Alien 3", "releaseYear": 1992, "rating": "R", "runtime": 114, "freshness": 0.44},
  {"title": "Alien: Resurrection", "releaseYear": 1997, "rating": "R", "runtime": 109, "freshness": 0.54},
  {"title": "AVP: Alien vs. Predator", "releaseYear": 2004, "rating": "PG-13", "runtime": 101, "freshness": 0.21},
  {"title": "Aliens vs. Predator: Requiem", "releaseYear": 2007, "rating": "R", "runtime": 94, "freshness": 0.12},
  {"title": "Predator", "releaseYear": 1987, "rating": "R", "runtime": 104, "freshness": 0.78},
  {"title": "Predator 2", "releaseYear": 1990, "rating": "R", "runtime": 108, "freshness": 0.25},
  {"title": "Predators", "releaseYear": 2010, "rating": "R", "runtime": 107, "freshness": 0.64},
  {"title": "Amelie", "releaseYear": 2001, "rating": "R", "runtime": 122, "freshness": 0.89},
  {"title": "From Justin to Kelly", "releaseYear": 2003, "rating": "PG", "runtime": 81, "freshness": 0.10},
  {"title": "Glitter", "releaseYear": 2001, "rating": "PG-13", "runtime": 104, "freshness": 0.07},
  {"title": "Gigli", "releaseYear": 2003, "rating": "R", "runtime": 121, "freshness": 0.06},
  {"title": "The Adventures of Pluto Nash", "releaseYear": 2002, "rating": "PG-13", "runtime": 95, "freshness": 0.05},
  {"title": "Primer", "releaseYear": 2004, "rating": "PG-13", "runtime": 77, "freshness": 0.71},
  {"title": "My Best Friend's Wedding", "releaseYear": 1997, "rating": "PG-13", "runtime": 105, "freshness": 0.71},
  {"title": "Psycho", "releaseYear": 1960, "rating": "R", "runtime": 109, "freshness": 0.96},
  {"title": "Breakfast at Tiffany's", "releaseYear": 1961, "rating": "G", "runtime": 115, "freshness": 0.88},
  {"title": "The Breakfast Club", "releaseYear": 1985, "rating": "R", "runtime": 97, "freshness": 0.89},
  {"title": "The King of Kong: A Fistful of Quarters", "releaseYear": 2007, "rating": "PG-13", "runtime": 79, "freshness": 0.97},
  {"title": "Love Actually", "releaseYear": 2003, "rating": "R", "runtime": 135, "freshness": 0.63},
  {"title": "Elf", "releaseYear": 2003, "rating": "PG", "runtime": 97, "freshness": 0.84},
  {"title": "Paul Blart: Mall Cop", "releaseYear": 2009, "rating": "PG", "runtime": 91, "freshness": 0.33},
  {"title": "The Princess Bride", "releaseYear": 1987, "rating": "PG", "runtime": 98, "freshness": 0.97},
  {"title": "No Country for Old Men", "releaseYear": 2007, "rating": "R", "runtime": 122, "freshness": 0.93},
  {"title": "Guardians of the Galaxy", "releaseYear": 2014, "rating": "PG-13", "runtime": 121, "freshness": 0.91},
  {"title": "Roman Holiday", "releaseYear": 1953, "rating": "NR", "runtime": 118, "freshness": 0.98},
  {"title": "Bridesmaids", "releaseYear": 2011, "rating": "R", "runtime": 125, "freshness": 0.90},
  {"title": "Her", "releaseYear": 2013, "rating": "R", "runtime": 126, "freshness": 0.94},
  {"title": "The Neverending Story", "releaseYear": 1984, "rating": "PG", "runtime": 102, "freshness": 0.81},
  {"title": "Spy", "releaseYear": 2015, "rating": "R", "runtime": 119, "freshness": 0.93},
  {"title": "Away We Go", "releaseYear": 2009, "rating": "R", "runtime": 98, "freshness": 0.67},
  {"title": "The Social Network", "releaseYear": 2010, "rating": "PG-13", "runtime": 120, "freshness": 0.96}
]
